# Site settings
title: raketenbasis.com
email: info@raketenbasis.com
description: Powered by Jekyll
baseurl: ""
url: "https://raketenbasis.com"
twitter_username: raketenbasis
github_username:  raketenbasis

# Build settings
markdown: kramdown
